version: '3.8'
services:
  gateway:
    build: ./gateway
    image: docker_gateway
    container_name: docker_gateway
    ports:
      - "8080:8080"
    depends_on:
      - service
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./service
    image: docker_service
    container_name: docker_service
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  db:
    image: postgres:13.7-alpine
    container_name: shareIt-postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root